# Site settings
title: N42
email: n42team@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  N42라는 이름으로 스타트업을 새롭게 시작합니다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://n42corp.com" # the base hostname & protocol for your site
twitter_username: n42team
github_username:  n42corp

# Build settings
markdown: kramdown
