baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://team.daangn.com" # the base hostname & protocol for your site

# Site settings
title: Danggeun Market Inc.
email: market@daangn.com
description: "당근마켓 팀 페이지 입니다."

about: "당근마켓의 비전은 “동네 이웃 간 활발한 교류와 연결을 통해 사람들의 삶을 더 행복하게 만드는 것”이에요.</br>지역 내에서 발생하는 모든 개인 간의 거래정보(중고거래, 구인, 지역생활정보 등)가 모이고</br>그 정보들이 따뜻한 문화 안에서 교류되는 세상을 꿈꾸고 있어요.</br>당근마켓은 중고거래에서 시작하지만 지역커뮤니티 및 정보 서비스를 지향합니다."

history:
- title: '소프트뱅크 벤처스, 카카오벤처스, 스트롱벤처스, 캡스톤파트너스로부터 68억 투자유치(Series B Round)'
  date: '2018.05'
  pic: investment2
  
- title: '가입자 100만 달성, 지역광고주를 위한 광고주센터(https://ad.daangn.com) 오픈'
  date: '2018.01'
  pic: icon
  
- title: Google Play 2017 올해를 빛낸 인디 앱 선정
  date: '2017.12'
  pic: google

- title: 아이폰, 안드로이드 합쳐서 100만 다운로드 달성
  date: '2017.10'
  pic: million

- title: "'(주)엔사십이'에서 '(주)당근마켓'으로 사명 변경'"
  date: '2016.12'
  pic: business

- title: "케이큐브 벤처스, 캡스톤파트너스, 스트롱벤처스 투자사로 부터 13억 투자유치(Series A Round)"
  date: '2016.12'
  pic: investment

- title: "'판교장터'에서 '당근마켓'으로 서비스명 변경, 분당 지역 오픈, 전화번호 기반으로 변경"
  date: '2015.10'
  pic: icon

- title: "판교장터 아이폰, 안드로이드 서비스 오픈 (직장인 기반) 및 법인 '(주)엔사십이' 설립"
  date: '2015.07'
  pic: start

media:
- content: 'MBN방송 현실남녀2 14회 - 정가은이 사용하는 당근마켓'
  date: '2018.11'
  url: https://www.youtube.com/watch?v=zk5aSjRIddM&feature=youtu.be&t=402

- content: "택배·퀵으로 거래할 수 없는 중고거래 서비스의 정체"
  date: '2018.11'
  url: http://naver.me/F3rNgo9H

- content: "‘당근마켓’은 어떻게 우리 동네의 핫한 ‘온라인 벼룩 시장’이 됐을까?"
  date: '2018.10'
  url: https://insidestory.kr/21288

- content: "성장폭 큰 앱 ‘유튜브’·성장비 높은 앱 ‘넷플릭스’"
  date: '2018.10'
  url: http://www.zdnet.co.kr/news/news_view.asp?artice_id=20181016084241&type=det&re=zdk
  
- content: "[최영진 기자의 ‘라이징 스타트업’(30) 당근마켓] 지역 생활정보 플랫폼 꿈꾼다"
  date: '2018.08'
  url: http://jmagazine.joins.com/economist/view/322427
  
- content: "육아맘 사로잡은 스타트업, 잘나가네"
  date: '2018.06'
  url: http://m.fnnews.com/news/201806081702407044

- content: "[IT&FUTURE]김용현·김재현 당근마켓 공동대표 \"동네 이웃과 중고거래, 믿을만 하겠죠\""
  date: '2018.05'
  url: http://view.asiae.co.kr/news/view.htm?idxno=2018052810355950858

- content: "소프트뱅크벤처스 스타트업 \"내일의 '유니콘' 바로 나\""
  date: '2018.05'
  url: http://www.zdnet.co.kr/news/news_view.asp?artice_id=20180517160809&type=det&re=

- content: "소프트뱅크벤처스, 당근마켓에 45억원 투자"
  date: '2018.04'
  url: http://www.zdnet.co.kr/news/news_view.asp?artice_id=20180424082614&type=det&re=

- content: "(영상) KBC 광주방송 뉴스에 소개된 당근마켓"
  date: '2018.04'
  url: https://youtu.be/SzWhApgP8PE

- content: "당근마켓, 중고 시장에서 지역 커뮤니티 플랫폼으로! - 아웃스텐딩"
  date: '2018.02'
  url: http://outstanding.kr/carrotmarket20180221/
  
- content: "(영상) YTN사이언스 녹색의 꿈에 당근마켓 소개된 영상"
  date: '2018.02'
  url: https://www.youtube.com/watch?v=Ii5flAhtM5c

- content: "[와이즈앱 비교하기 #74] 11월 중고 거래 앱 사용자 동향"
  date: '2017.12'
  url: http://platum.kr/archives/92856

- content: "넘쳐나는 안 입는 옷, 버리기 아깝다면? 동네 주민끼리 중고거래 앱 '당근마켓'"
  date: '2017.12'
  url: https://sharehows.com/applay-carrot-market

- content: "[Startup’s Story #381] 한 달에 25번 켜는 중고 거래 앱"
  date: '2017.11'
  url: http://platum.kr/archives/91626

- content: "(영상) MBC 경제매거진M에 소개된 당근마켓"
  date: '2017.08'
  url: https://www.youtube.com/watch?v=rnP7GeYq18Q&t=107s

- content: "[대한민국 모바일 어워드 2017 '4월의 모바일'] 이웃과 직접…모바일 중고거래 '당근마켓'"
  date: '2017.04'
  url: http://news.mt.co.kr/mtview.php?no=2017042613580872654

- content: "'차세대 벼룩시장을 꿈꾸며'... 지역 중고 거래 플랫폼 '당근마켓'"
  date: '2017.03'
  url: http://view.asiae.co.kr/news/view.htm?idxno=2017031715320315859

- content: "동네사람 직접 만나 중고품 직거래··사기당할 염려없으니'당근'이지"
  date: '2016.12'
  url: http://www.womaneconomy.kr/news/articleView.html?idxno=52662

- content: "[2020 유니콘]우리동네 이웃과 따뜻한 거래 `당근마켓`"
  date: '2016.04'
  url: http://www.etnews.com/20160322000150

- content: "`카카오 키즈` 스타트업, 인터넷생태계에 새 씨앗 뿌린다"
  date: '2016.01'
  url: http://www.etnews.com/20160126000113

- content: "동네 주민 이어주는 중고장터 '당근마켓'"
  date: '2015.07'
  url: http://platum.kr/archives/92856

team_description: "\"당근마켓은 여러 분야의 뛰어난 인재들이 모여 즐겁게 일하고 있어요.\""

# Team names, titles and social links
people:
- name: 김재현(Paul)
  row: 1
  pic: paul
  position: Co CEO (Data Analysis)
  social:
    - title: home
      url: http://jaehyun.kr/
    - title: twitter
      url: https://twitter.com/jaehyun

- name: 김용현(Gary)
  row: 1
  pic: gary
  position: Co CEO (Project Management)
  social:
    - title: medium
      url: https://medium.com/@yongal4783
    - title: facebook
      url: https://www.facebook.com/yongal4783

- name: 정창훈(Seapy)
  row: 1
  pic: seapy
  position: CTO (Software Engineer)
  social:
    - title: home
      url: https://www.iamseapy.com/
    - title: twitter
      url: https://twitter.com/seapy
    - title: youtube
      url: https://www.youtube.com/c/seapy

- name: 정우람(Kai)
  row: 2
  pic: kai
  position: Android Developer
  social:
    - title: home
      url: https://kaidroid.me/

- name: 박선영(Phoebe)
  row: 2
  pic: phoebe
  position: Server Developer
  social:

- name: 이보현(Blair)
  row: 2
  pic: blair
  position: Marketer
  social:
    - title: instagram 
      url: https://www.instagram.com/bbohyuning/
    - title: facebook
      url: https://www.facebook.com/bohyun.lee.73

- name: 전무익(Ed)
  row: 3
  pic: ed
  position: Machine Learning Engineer
  social:
    - title: instagram 
      url: https://www.instagram.com/muik13/
    - title: twitter
      url: https://twitter.com/muik

- name: 정란희(Lucy)
  row: 3
  pic: lucy
  position: UI/UX Designer
  social:

- name: 김현학(Wayne)
  row: 3
  pic: wayne
  position: Server Developer
  social:

- name: 김대권(Ben)
  row: 4
  pic: ben
  position: Software Engineer
  social:

- name: 한재원(Jeff)
  row: 4
  pic: jeff
  position: Marketer
  social:
    - title: facebook
      url: https://www.facebook.com/artistonea
    - title: instagram 
      url: https://www.instagram.com/hanjae_92/

- name: 황병국(Marty)
  row: 4
  pic: marty
  position: iOS Developer
  social:
    - title: facebook
      url: https://www.facebook.com/bkhwang82
    - title: home
      url: https://magi82.github.io/

- name: 최정윤(Nicole)
  row: 5
  pic: nicole
  position: Marketer(Part Leader of Marketing)
  social:
    - title: facebook
      url: https://www.facebook.com/jy.choi.777

- name: 이웅원(Matthew)
  row: 5
  pic: matthew
  position: Machine Learning Engineer
  social:
    - title: facebook
      url: https://www.facebook.com/dnddnjs

- name: 정재필(Sean)
  row: 5
  pic: sean
  position: Web Front-end Software Engineer
  social:
    - title: twitter
      url: https://twitter.com/J2P_
    - title: home
      url: http://blog.j2p.io/

joinus_description: "\"당근마켓 서비스를 즐겁게 만들어갈 멋진 동료를 찾고 있어요. 상시 채용중입니다.\""

joinus:

- position: 개발자
  pic: recruit-developer
  sub-position: 
    - content: 당근마켓 채용 페이지
      url: https://www.notion.so/daangn/Join-Us-07ca1fda22584d60a48ef43a8cf9bab0

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:market@daangn.com
  - title: medium
    url: https://medium.com/daangn
  - title: facebook
    url: https://www.facebook.com/daangn/
  - title: github
    url: https://github.com/daangn

# 회사 정보
address: 서울특별시 서초구 반포대로28길 20 두원빌딩 3층

# Build settings
markdown: kramdown
permalink: pretty


