# Site settings
title: 당근마켓
email: market@daangn.com
description: > # this means to ignore newlines until "baseurl:"
  Danggeun Market Inc.<br/>
  주소: 성남시 분당구 판교역로 10번길 23. 201호 (판교지점)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://team.daangn.com" # the base hostname & protocol for your site
twitter_username: n42corp
github_username:  n42corp

# Build settings
markdown: kramdown

image: https://pangyo.towneers.com/images/icons/Icon_512x512.png
