# Site settings
title: N42
email: n42team@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  (주)엔사십이<br/>
  주소:서울특별시 서초구 서초대로 397 부띠크 모나코 A동 1608호
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://n42corp.com" # the base hostname & protocol for your site
twitter_username: n42team
github_username:  n42corp

# Build settings
markdown: kramdown
